<%@ page language="java" contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="tiles" uri="http://tiles.apache.org/tags-tiles" %>
<%@ taglib prefix="washers" tagdir="/WEB-INF/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

	<header class="row game-score-header">
		<div class="home-score col-xs-6">
			<div class="team-type">HOME</div>
			<div class="score"><fmt:formatNumber pattern="00" value="${game.homeScore}" /></div>
		</div>
		<div class="guest-score col-xs-6">
			<div class="team-type">GUEST</div>
			<div class="score"><fmt:formatNumber pattern="00" value="${game.guestScore}" /></div>
		</div>
	</header>

	<svg id="svg" version="1.1" xmlns="http://www.w3.org/2000/svg"
		xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
		width="320px" height="280px">
       <rect id="svg-background" x="0" y="0" width="320" height="280" />
       <rect id="box-edge" x="60" y="40" width="200" height="200" />
       <rect id="box" x="80" y="60" width="160" height="160" />
       <g>
           <circle id="cup-edge" cx="160" cy="140" r="26.5" />
           <circle id="cup" cx="160" cy="140" r="23.5" />
       </g>
	</svg>
	
	<div class="frame-number">
		<span>ROUND ${frame.number} (${frame.type.label})</span>
	</div>
	
	<header class="row frame-score-header">
		<div class="score home-score col-xs-6 ${frame.firstTeam == 'HOME' ? 'active' : ''}">
			<div class="team-type">${frame.homePlayer.name}</div>
			<div class="score"><fmt:formatNumber pattern="00" value="${frame.homePoints}" /></div>
		</div>
		<div class="score guest-score col-xs-6 ${frame.firstTeam == 'GUEST' ? 'active' : ''}">
			<div class="team-type">${frame.guestPlayer.name}</div>
			<div class="score"><fmt:formatNumber pattern="00" value="${frame.guestPoints}" /></div>
		</div>
	</header>
	
	<!-- ATTEMPTS -->
	<div class="attempts-container">
		
		<table class="attempts-table">
			<thead>
				<tr>
					<th>&nbsp;</th>
					<th>1</th>
					<th>2</th>
					<th>3</th>
					<th>4</th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td class="player player-${frame.firstTeam}" data-team-type="${frame.firstTeam}" data-player-id="${frame.firstPlayer.id}">${frame.firstPlayer.name}</td>
					<td class="attempt-score" data-frame-attempt-number="1" data-player-attempt-number="1"></td>
					<td class="attempt-score" data-frame-attempt-number="2" data-player-attempt-number="2"></td>
					<td class="attempt-score" data-frame-attempt-number="3" data-player-attempt-number="3"></td>
					<td class="attempt-score" data-frame-attempt-number="4" data-player-attempt-number="4"></td>
				</tr>
				<tr>
					<td class="player" data-team-type="${frame.secondTeam}" data-player-id="${frame.secondPlayer.id}">${frame.secondPlayer.name}</td>
					<td class="attempt-score" data-frame-attempt-number="5" data-player-attempt-number="1"></td>
					<td class="attempt-score" data-frame-attempt-number="6" data-player-attempt-number="2"></td>
					<td class="attempt-score" data-frame-attempt-number="7" data-player-attempt-number="3"></td>
					<td class="attempt-score" data-frame-attempt-number="8" data-player-attempt-number="4"></td>
				</tr>
			</tbody>
		</table>
		
		<button id="undoButton" class="btn btn-default hidden"><i class="fa fa-undo"></i> Undo</button>
		<button id="frameSaveButton" class="btn btn-orange hidden"><i class="fa fa-save"></i> Save</button>
		
	</div>
	
	<form:form modelAttribute="frame">
		<form:hidden path="id" />
		<form:hidden id="homePlayerId" path="homePlayer.id" />
		<form:hidden id="guestPlayerId" path="guestPlayer.id" />
	</form:form>
	
	<spring:url var="actionUrl" value="/frames/{frameId}/attempts">
		<spring:param name="frameId" value="${frame.id}" />
	</spring:url>
	
	<!-- USE THIS FORM TO SUBMIT THE JSON DATA GENERATED BY SVG/JAVASCRIPT -->
	<form id="attemptsForm" action="${actionUrl}" method="post">
		<input type="hidden" name="jsonData" />
	</form>
